POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "My First Blog",
    "author": "Anurag",
    "url": "Hello World",
    "likes": 1000
}

###
GET http://localhost:3003/api/blogs